### ISSUE TITLE
cursor keys fly the drone very slowly

### ISSUE THREAD

**Issue by gotgot1995** [SMerrony/telloterm#2]
Hello there, good work with the go lang on this project ;)

I tried to pilot my new drone using your telloterm package and I had some small issue.
Using the 'w|a|s|d' keys, I could fly upward, downward, turn left and right. Although the 'cursor keys' only fly the drone very slowly. I tried hitting the '+' key, but it didn't seem to go any faster.
## Expected Behavior

Drone should move forward/backward/left/right actively.

## Current Behavior

Drone moves very slowly in the corresponding direction.

## Steps to Reproduce (for bugs)

1. Turn on the tello drone (and connect to its Wi-Fi)
2. Launch the telloterm
3. Try to use the cursor keys to go forward/backward/left/right

## Your Environment

* Go Version used:
go version go1.11 linux/amd64
* Tello Package Version or Date:
v0.8.3
* Operating System and version:
Description:	Debian GNU/Linux 9.5 (stretch)
Release:	9.5
Codename:	stretch

**Comment by SMerrony** [comment]
Two things...
Did you use the plus key on the main keyboard, or the one on the numeric pad?  I don't think the numeric pad one works on some systems, and that is a limitation of one of the Go packages I am using.

Also, the speed is preset to 33% - which was deliberate...

**Comment by gotgot1995** [comment]
Hi.

I'm using the + key on the main keyboard.
Okay, I'll increase the speed preset manually in the code.
